WebMemoryGame/Controllers/PlayGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMemoryGame.Models;

namespace WebMemoryGame.Controllers
{
    public class PlayGameController : Controller
    {
        // GET: PlayGame
        public ActionResult Index()
        {
            ViewBag.Naslov = "Stellar 8 logic game";
            ViewBag.Nivo = 4;

            if (Session["Start"] == null) Session["Start"] = false;
            ViewBag.Start = Session["Start"];

            if (Session["Login"]!=null && Convert.ToBoolean(Session["Login"]))
            {
                ViewBag.Login = true;
            }
            else
            {
                ViewBag.Login = false;
            }
            return View();
        }

        public ActionResult Register(mem_korisnici MK)
        {
            ViewBag.Naslov = "Stellar 8 logic game";

            if (MK.email!=null)
            {
                var errorNum = ModelState.Count;
                return RedirectToAction("Login");
            }
            return View();
        }
        public ActionResult Login(mem_korisnici MK)
        {
            ViewBag.Naslov = "Stellar 8 logic game";

            if (MK.username != null)
            {
                Session["Login"] = true;
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session["Login"] = null;
            Session["Start"] = false;
            Session["StartTime"] = null;
            return RedirectToAction("Index");
        }

        public ActionResult StartGame()
        {
            if (Session["Login"] != null && Convert.ToBoolean(Session["Login"]))
            {
                kreirajNovuTabelu();
                Session["Start"] = true;
                Session["StartTime"] = DateTime.Now;
            }
            return RedirectToAction("Index");
        }
        public ActionResult StopGame()
        {
            zaustaviIgru();
            return RedirectToAction("Index");
        }
         public ActionResult GameTimer()
        {
            var vreme = (DateTime.Now - Convert.ToDateTime(Session["StartTime"]));
            var minuti = Math.Floor(vreme.TotalMinutes);
            var odgovor = string.Empty;
            if (minuti >= 10)
            {
                zaustaviIgru();
                odgovor = "STOP";
            }
            else
            {
                var sekundi = (vreme).TotalSeconds - minuti * 60;
                odgovor = minuti.ToString("00") + ":" + sekundi.ToString("00");
            }
            return Content (odgovor);
        }
        private MemTabla kreirajNovuTabelu()
        {
            var lok_tabla = new MemTabla();

            return lok_tabla;
        }
        private void zaustaviIgru()
        {
            Session["Start"] = false;
            Session["StartTime"] = null;
        }
    }
}

WebMemoryGame/Views/PlayGame/GamePartial.cshtml
<p>
    @Html.ActionLink("Заустави игру", "StopGame", "PlayGame", new
    {@*onclick = "zaustaviIgru();"*@})
</p>
<table>
    @for (var i = 0; i < ViewBag.Nivo; i++)
    {
        <tr>
            @for (var j = 0; j < ViewBag.Nivo; j++)
            {
                <td><button class="memBtn" id="btn_@((i * ViewBag.Nivo + j).ToString("00"))" onclick="stisniDugme(this);">*</button></td>
            }
        </tr>
    }
</table>

<script>
    var interval;
    interval = setInterval(function () {
        $.get("./PlayGame/GameTimer", function (data) {
            if (data === "STOP") {
                window.location.reload();
            }
            else {
                $("#lblTOG").html(data);
            }
        });

    }, 1000);
</script>

WebMemoryGame/Views/PlayGame/Index.cshtml
@{
    ViewBag.Title = "Memory Game";
    Layout = "~/Views/PlayGame/_LayoutPlay.cshtml";
}
<div class="content">
    <h2>@ViewBag.Naslov</h2>
    @if (!ViewBag.Login)
    {
        <p>
            @Html.ActionLink("Региструј се", "Register", "PlayGame")
        </p>
        <p>
            @Html.ActionLink("Пријави се", "Login", "PlayGame")
        </p>
    }
    else
    {
        <p>
            @Html.ActionLink("Одјави се", "Logout", "PlayGame")
        </p>
        <p>
            @Html.Label("lblVreme", "Протекло време")
            @Html.Label("TimeOfGame", "00:00", new { id = "lblTOG" })
        </p>
        if (ViewBag.Start)
        {
            @Html.Partial("GamePartial", null, ViewData)
        }
        else
        {
            @Html.Partial("IntroPartial", null, ViewData)

        }
    }
</div>

WebMemoryGame/Views/PlayGame/IntroPartial.cshtml
<p>
    @Html.ActionLink("Почни игру", "StartGame", "PlayGame", new
    {@*onclick = "pokreniIgru();"*@})
</p>
<table>
    @for (var i = 0; i < ViewBag.Nivo; i++)
    {
        <tr>
            @for (var j = 0; j < ViewBag.Nivo; j++)
            {
                <td><button class="memBtn" id="btn_@((i * ViewBag.Nivo + j).ToString("00"))" onclick="stisniDugme(this);">*</button></td>
            }
        </tr>
    }
</table>
<script>
    var interval;
    clearInterval(interval);

    setInterval(function () {
        var i = Math.floor(Math.random() * 4 * 4);
        var dugme = $('#btn_' + pad(i, 2));
        var boja = dugme.css("background-color");
        if (Math.floor(Math.random() * 2) === 1) {
            dugme.css("background-color", "rebeccapurple");
        }
        else {
            dugme.css("background-color", "mediumpurple");
        }      
    }, 300);

    function pad(num, size) {
        var s = num + "";
        while (s.length < size) s = "0" + s;
        return s;
    }
</script>

WebMemoryGame/Views/PlayGame/Login.cshtml
@model WebMemoryGame.Models.mem_korisnici

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/PlayGame/_LayoutPlay.cshtml";
}

<h2>@ViewBag.Naslov</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })     
        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebMemoryGame/Views/PlayGame/Register.cshtml
@model WebMemoryGame.Models.mem_korisnici

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/PlayGame/_LayoutPlay.cshtml";
}
    <h2>@ViewBag.Naslov</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Register:</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fullname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fullname, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

WebMemoryGame/Views/PlayGame/_LayoutPlay.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @Styles.Render("~/Content/css")
    
    @RenderSection("head", required: false)
</head>
<body>
    <header>
        <img src="~/Assets/imgs/stellar8-2.png" class="siteLogo" /> <h1>Memory Game</h1>
    </header>
    @RenderBody()
    @Scripts.Render("~/Bundles/js")
</body>
</html>